name: 🔴 Bug Report
description: Report any bugs you encounter.
title: "🔴 [Bug] Issue with <feature>: <brief description>"
labels: ["type:bug"]
assignees:
  - oskhar
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting this bug! Please fill out all sections below to help us address the issue more effectively.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we contact you if we need additional information? (optional)
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Provide a brief summary of the bug you encountered.
      placeholder: Briefly describe the bug.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Reproduction Steps
      description: Describe the steps to reproduce the bug.
      placeholder: Detailed steps to reproduce the bug.
    validations:
      required: true

  - type: textarea
    id: expected-result
    attributes:
      label: Expected Result
      description: What did you expect to happen?
      placeholder: Describe the expected outcome.
    validations:
      required: true

  - type: textarea
    id: actual-result
    attributes:
      label: Actual Result
      description: What actually happened?
      placeholder: Describe the actual outcome.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide details about your environment, including software version, OS, browser, and device used.
      placeholder: Software version, OS, browser, etc.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Paste relevant logs here. Logs will be automatically formatted as code.
      render: shell

  - type: dropdown
    id: version
    attributes:
      label: Software Version
      description: Select the software version you are using.
      options:
        - 1.0.0 (Stable)
      default: 0
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to abide by the project's [Code of Conduct](https://github.com/oskhar/init-repo-template/blob/master/code_of_conduct.md).
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
